Update error-code.md
Dynamsoft/barcode-reader-docs pull request #116
Opened 2020-12-29 09:46 UTC by claire-chan

2020-12-30 00:27 UTC, DMGithubPublisher requested changes
DMERR_INTERFACE_CONFLICT -> DMERR_LICENSE_INTERFACE_CONFLICT

2020-12-30 00:27 UTC, DMGithubPublisher commented on parameters/enum/error-code.md
> +  | `DMERR_INTERFACE_CONFLICT` | `EnumErrorCode_LICENSE_INTERFACE_CONFLICT` | -20006 | Interface InitLicenseFromLTS can not be used together with other license initiation interfaces. |
DMERR_INTERFACE_CONFLICT -> DMERR_LICENSE_INTERFACE_CONFLICT

2020-12-30 06:09 UTC, owenlyn0123 approved these changes

2021-01-07 10:10 UTC, owenlyn0123 approved these changes

2021-01-08 01:15 UTC, DMGithubPublisher approved these changes

2021-01-08 01:50 UTC, merged